version: "3.9"

services:

    minio:
        image: minio/minio
        hostname: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_storage:/data
        environment:
            MINIO_ROOT_USER: jibajibajibajiba
            MINIO_ROOT_PASSWORD: urusurusurus
        command: server --console-address ":9001" /data

    nginx:
        build: nginx/.
        ports:
            - 8079:80
        depends_on:
            - minio

    asp:
        build:
            context: ResizerASPNET/.
            dockerfile: ./ResizerASPNET/Dockerfile
        depends_on:
            - minio
        environment:
            API_ENDPOINT: api:80
            MINIO_NGINX_ENDPOINT: localhost:8079
            MINIO_ENDPOINT: minio:9000
            MINIO_ROOT_USER: jibajibajibajiba
            MINIO_ROOT_PASSWORD: urusurusurus
            BUCKET_NAME: cropper
        ports:
            - 8082:80
            - 8083:443

    api:
        build:
            context: ResizerAPI/.
            dockerfile: ./ResizerAPI/Dockerfile
        depends_on:
            - minio
        ports:
            - 7273:80
            - 7274:443
        environment:
            MINIO_NGINX_ENDPOINT: localhost:8079
            MINIO_ENDPOINT: minio:9000
            MINIO_ROOT_USER: jibajibajibajiba
            MINIO_ROOT_PASSWORD: urusurusurus
            BUCKET_NAME: cropper

volumes:
    minio_storage: {}
  